---
- name: build a Jenkins Service
  hosts: test_vagrant
  sudo: true
  remote_user: vagrant
  tasks:
  - name: remove running container
    script: ../auto/down.sh
  - name: pull meeting-server image
    docker:
      name: eid-summary-report
      image: 192.168.33.80:5000/meeting_server:{{BUILDNUMBER}}
      ports:
      - "8080:8080"