---
- name: build a Jenkins Service
  hosts: 192.168.33.10 ansible_ssh_user=vagrant ansible_ssh_pass=vagrant
  sudo: true
  remote_user: vagrant
  tasks: 
    - name: Copy project jar
      copy:
        src: ../target/meeting-0.0.1-SNAPSHOT.jar
        dest: /var