---
- name: build a Jenkins Service
  hosts: test_vagrant
  sudo: true
  remote_user: vagrant
  tasks:
    - name: Stop old project
      sudo: yes
      sh: deploy_jar.sh
    - name: Copy project jar
      copy:
        src: ../target/meeting-0.0.1-SNAPSHOT.jar
        dest: /var