---
- name: build a Jenkins Service
  hosts: 192.168.33.10 ansible_ssh_user=vagrant ansible_ssh_pass=vagrant
  sudo: true
  remote_user: vagrant
  tasks:
    - name: Run project jar
      command: java -jar /var/meeting-0.0.1-SNAPSHOT.jar